env:
  es2021: true
  node: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  no-console: "off"
  import/extensions: "off"
  quotes: ["error", "double", { "allowTemplateLiterals": true }]
  comma-da: ["error", "never"]
